/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
 /*\title Blinky LED
 * \abstract An LED is blinking based on the timing given by a wait function.
 * \description A wait function is used to add delays between switching on and switching off an LED
 *              on port pin P00.5.
 *
 * \name Blinky_LED_1_KIT_TC275_LK
 * \version V1.0.2
 * \board AURIX TC275 lite Kit, KIT_AURIX_TC275_LITE, TC27xTP_D-Step
 * \keywords AURIX, Blinky_LED_1, Blinky, LED, Lite
 * \documents https://www.infineon.com/aurix-expert-training/Infineon-AURIX_Blinky_LED_1_KIT_TC275_LK-TR-v01_00_02-EN.pdf
 * \documents https://www.infineon.com/aurix-expert-training/TC27D_iLLD_UM_1_0_1_12_0.chm
 * \lastUpdated 2021-06-29
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "InfineonArduinoLike/Spi.h"
#include "Bsp.h"

IfxCpu_syncEvent g_cpuSyncEvent = 0;

IfxQspi_SpiSlave MySpiSlave;
SpiSlavePins_t MySpiSlavePins =
{
    &IfxQspi1_SCLKA_P10_2_IN,
    &IfxQspi1_MTSRA_P10_3_IN,
    &IfxQspi1_MRST_P10_1_OUT,
    &IfxQspi1_SLSIA_P11_10_IN
};

SpiChannelConfig MySpiSlaveConfig =
{
    &IfxQspi0_SLSO0_P20_8_OUT,
    1000010,
    0,
    SpiIf_ShiftClock_shiftTransmitDataOnTrailingEdge,
    SpiIf_DataHeading_msbFirst
};

uint8 SpiTx[3] = {0x34, 0x55, 0xFA};
uint8 SpiRx[3];

int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    Ifx_TickTime time50ms = IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, 50);
    Spi_SlaveInit(&MySpiSlave, &MySpiSlavePins, &MySpiSlaveConfig);
    while(1)
    {
      wait(time50ms);
      Spi_SlaveExchange(&MySpiSlave, SpiTx, SpiRx, 3);
    }
    return (1);
}
